CREATE DATABASE IF NOT EXISTS REGISTRO_LOGIN;

USE REGISTRO_LOGIN;

CREATE TABLE IF NOT EXISTS usuarios (
    username VARCHAR(50) PRIMARY KEY,
    pass VARCHAR(255) NOT NULL
);

TRUNCATE TABLE usuarios;

SELECT * FROM usuarios;